- name: add ssh keys for the remote user
  become: true
  authorized_key:
    key: "{% for key in query('fileglob', 'ssh_keys/{{ deploy_env }}/*') %}{{ lookup('file', key) ~ '\n'}}{% endfor %}"
    user: "{{ ansible_ssh_user }}"
    exclusive: yes

- name: add ssh keys for the deploy user
  become: true
  authorized_key:
    key: "{% for key in query('fileglob', 'ssh_keys/{{ deploy_env }}/*') %}{{ lookup('file', key) ~ '\n'}}{% endfor %}"
    user: "{{ deploy_user }}"
    exclusive: yes
